import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Activity Manager",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <AppRouterCacheProvider>
      {props.children}
    </AppRouterCacheProvider>
    </body>
    </html>
  );
}
